title: Portfolio - Jakob Nacanaynay
email: jnac8080@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello,
  I'm a student at Mountlake Terrace High School that does coding stuff and likes writing sometimes. I don't consider myself a particularly interesting person.
  Loves: Learning, coding, writing, dogs
  Hates: Learning, coding, writing
  That’s about it,
  ---
  ~ Jakob Nacanaynay

baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jakobnacanaynay
github_username:  j-nac

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
